#!/bin/bash
if [ ! "`whoami`" = "root" ]
then
	echo "You must run this script as root."
	exit 1
fi
PS3='Do you want to install, remove or update the program? Make your choice below.
Your choice: '
options=("Install" "Remove" "Update" "Quit")
select opt in "${options[@]}"
do
	case $opt in
		"Install")
			echo "OK. We install AutoDL now"
			echo "Checking now for required packages..."
			apt update
			echo "y" | apt install ffmpeg wget git
			echo "Done..."
			sleep 2
			echo "Second we install YouTube-DL"
			curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
			chmod a+rx /usr/local/bin/youtube-dl
			echo "Now we install AutoDL"
			cd /
			mkdir -p .git-autodl
			cd .git-autodl
			git clone https://github.com/mhognl/AutoDL.git
			cp AutoDL/autodl /usr/local/bin
			chmod +x /usr/local/bin/autodl
			mkdir -p /ytdownloads
			touch /ytdownloads/list.txt
			chown -R root:root /ytdownloads
			chmod -R 777 /ytdownloads
			echo "Finished!"
			echo "Now you can run the command 'autodl' as normal user!"
		;;
		
		"Remove")
			echo "OK. We remove AutoDL now. Do you really want this? We will be asking for each package"
				PS3='Yes or no: '
				options=("Yes" "No")
				select quest in "${options[@]}"
				do
					case $quest in
						"Yes")
							echo "OK. We uninstall AutoDL now"
							PS3='Do you want to remove ffmpeg?
Yes or no: '
							options=("Yes" "No")
							select ffmpeg in "${options[@]}"
							do
								case $ffmpeg in
									"Yes")
										echo "Purging now..."
										echo "y" | apt purge ffmpeg
										echo "Done..."
										sleep 2
										break
									;;
									
									"No")
										break
									;;
									*) echo "invalid option $REPLY";;
								esac
							done
							
							PS3='Do you want to remove wget?
Yes or no: '
							options=("Yes" "No")
							select wget in "${options[@]}"
							do
								case $wget in
									"Yes")
										echo "Purging now..."
										echo "y" | apt purge wget
										echo "Done..."
										sleep 2
										break
									;;
									
									"No")
										break
									;;
									*) echo "invalid option $REPLY";;
								esac
							done
							
							PS3='Do you want to remove git?
Yes or no: '
							options=("Yes" "No")
							select git in "${options[@]}"
							do
								case $git in
									"Yes")
										echo "Purging now..."
										echo "y" | apt purge git
										echo "Done..."
										sleep 2
										break
									;;
									
									"No")
										break
									;;
									*) echo "invalid option $REPLY";;
								esac
							done
							
							PS3='Do you want to remove YouTube-DL?
Yes or no: '
							options=("Yes" "No")
							select ytdl in "${options[@]}"
							do
								case $ytdl in
									"Yes")
										echo "Removing now..."
										rm /usr/local/bin/youtube-dl
										echo "Done..."
										sleep 2
										break
									;;
									
									"No")
										break
									;;
								esac
							done
							
							echo "Cleaning now..."
							echo "y" | apt autoremove
							echo "y" | apt autoclean
							rm -r /ytdownloads /.git-autodl /usr/local/bin/autodl
							echo "Finished!"
							echo "We hope you enjoyed AutoDL!"
							sleep 2
							exit
						;;
						
						"No")
							break
						;;
						*) echo "invalid option $REPLY";;
					esac
				done
		;;
		
		"Update")
			echo "OK. We update AutoDL now"
			echo "Updating..."
			rm /usr/local/bin/autodl /usr/local/bin/youtube-dl
			curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
			chmod a+rx /usr/local/bin/youtube-dl
			cd /.git-autodl
			rm -r AutoDL
			git clone https://github.com/mhognl/AutoDL.git
			cp AutoDL/autodl /usr/local/bin/autodl
			chmod +x /usr/local/bin/autodl
			echo "Finished! Enjoy!"
		;;

		"Quit")
			break
		;;
		
		*) echo "invalid option $REPLY";;
	esac
done
